### PR TITLE
Vendor Thrift

### LINKED ISSUE #86: error occurs when build example because of thrift
I'm trying to build example and run. Found some errors and need help to fix.

When depends on github.com/apache/thrift @ 0.10.0 (which is the lastest version tag). The build result is below
image

and then goto line 333 of github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go
image

the type of self2.processorMap is thrift.TProcessorFunction. And the definition of thrift.TProcessorFunction in github.com/apache/thrift @ 0.10.0 is below
image

But the Process function's implemention in scribeProcessorLog is defined like this
image

### PR DESCRIPTION
**Pull request by agparadiso**
this PR pins thrift to the working version. commit #847ecf3c1de8b297d6a29305b9f7871fcf609c36

before zipkin was failing to build, returning:

```
# github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe
gen-go/scribe/scribe.go:270: assignment count mismatch: 2 = 1
gen-go/scribe/scribe.go:317: cannot use scribeProcessorLog literal (type *scribeProcessorLog) as type thrift.TProcessorFunction in assignment:
	*scribeProcessorLog does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
gen-go/scribe/scribe.go:325: not enough arguments in call to processor.Process
	have (int32, thrift.TProtocol, thrift.TProtocol)
	want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
```

Closes #86

### CODE REVIEW

**Comment by jcchavezs** [comment]
Ping @basvanbeek @adriancole @marc-gr

**Comment by adriancole** [comment]
cc @kujtimiihoxha who opened #87 

need to make a choice one approach vs the other. I don't think tradeoffs are well explained here, so I can't make that call (not enough go ecosystem experience)

**Comment by basvanbeek** [comment]
I'm not a big fan of vendoring within a library. Has anybody tried to generate the thrift code from the latest dev version of the thrift compiler?

I will try this when back home. If that fails I will explore options of vendoring but these would not be on this last working commit but probably on last official thrift release.

**Comment by agparadiso** [comment]
@basvanbeek I've tried vendoring version 0.10.0 but it fails, returning this error
```
# github.com/Typeform/boombox/server/vendor/github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe
vendor/github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:333: cannot use scribeProcessorLog literal (type *scribeProcessorLog) as type thrift.TProcessorFunction in assignment:
	*scribeProcessorLog does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
vendor/github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:341: too many arguments in call to processor.Process
	have (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
	want (int32, thrift.TProtocol, thrift.TProtocol)
make[1]: *** [server-build-binary] Error 2
make: *** [app] Error 2
```

**Comment by jcchavezs** [comment]
I believe vendoring dependencies allow us to keep a safe API which is crucial with so many dependencies. In the other hand, since there is some work in zipkin-go, does it makes sense to keep this library stable and focus on zipkin-go and a future bridge? WDYT @basvanbeek

**Comment by basvanbeek** [comment]
I've regenerated the thrift code based on latest Go library and thrift compiler. This eliminates the need for vendoring at the library end.

**Pull request closed without merging**
