### PR TITLE
WIP: Support for 128 bit TraceIDs

### PR DESCRIPTION
**Pull request by basvanbeek**
This PR handles the ability of the tracer to work with 128 bit TraceIDs.

See: https://github.com/openzipkin/zipkin/issues/1298

### CODE REVIEW

**Comment by basvanbeek** [comment]
this PR has been tested with 64 bit traceID Zipkin instance and is backwards compatible if tracing with 128 bit traceIDs by simply having the high bits of the traceID be ignored. 

Sampling functionality is also solely on the low 64 bits.

This PR will be merged once Zipkin backend supports 128 bit TraceIDs.

**Comment by adriancole** [comment]
I ran the example against snapshot zipkin and looks great! 

```
   {
      "traceId": "15225468d9e004834ec2cc8befaf251f",
      "id": "3230ce0f79a9b1d9",
      "name": "mycomplexquery",
```

**Comment by adriancole** [comment]
ps for those unacclimated, here's what I did to test..

```
$ export GOPATH=$HOME/work
$ export PATH=$PATH:$GOPATH/bin
$ cd $GOPATH/src/github.com/openzipkin/zipkin-go-opentracing/examples/cli_with_2_services
$ git checkout -t -b 128bit-traceid origin/128bit-traceid
$ make
$ build/svc1&
$ build/svc2&
$ build/cli
```

**Comment by basvanbeek** [comment]
awesome... sounds like merge time to me!

**Pull request merged**
