### PR TITLE
Rename `_thrift` to `thrift` to make it easier to build this repo with Bazel

### PR DESCRIPTION
**Pull request by ZackButcher**
We're trying to make use of Zipkin over in [Istio](https://github.com/istio/), where we use [Bazel](https://bazel.build/) to build everything. Unfortunately, [Gazelle](https://github.com/bazelbuild/rules_go/tree/master/go/tools/gazelle), the tool Bazel uses to synthesize BUILD files, ignores directories that begin with an underscore. It does this is to ensure it has similar semantics to the standard `go build` tooling, which also ignores those directories.

With the changes in this PR the standard Bazel `new_go_repository` successfully builds this repo without a Bazel user having to synthesize BUILD files for every package. Note that I had to mark the `scribe-remote.go` file with a golang build tag to avoid building it, since `make test` (i.e. `go test -v -race -cover ./...`) doesn't ignore the `_thrift` directory any more. I could not get that file to build successfully at openzipkin/zipkin-go-opentracing HEAD due to the unqualified import of `scribe` anyway.

### CODE REVIEW

**Comment by ZackButcher** [comment]
Looks like the linters don't like a lot of the Thrift generated code since they're now running over the Thrift dir. Investigating workarounds now.

**Comment by basvanbeek** [comment]
Now you know why it has the underscore. For reference: https://github.com/openzipkin/zipkin-go-opentracing/issues/42

Typically `go build` and `go install` have no issues with making sure the go files under _thrift are pulled in when building the binary. When it comes to `go test` the files ate indeed ignored which in this case is very welcome.

**Comment by ZackButcher** [comment]
Would you be opposed to updating `make lint` to something along the lines of the following?

    golint ./... | grep --invert-match -E '^.*\.pb\.go|^thrift'

**Comment by basvanbeek** [comment]
since the side effects are gone, I've merged this one. thanks for the contribution

**Pull request merged**
